### ISSUE TITLE
probability distribution chapter does not seem to open

### ISSUE THREAD

**Issue by leios** [algorithm-archivists/aaa-py#23]
I get the following request error: `"GET /contents/probability_distributions/distributions.html) HTTP/1.1" 404 -`

**Comment by Amaras** [comment]
I found the cause of the issue.
The AAA `SUMMARY.md` file has a trailing space, which is not something that the code had taken into account.
We need to follow Postel's law: "be conservative in what you send, be liberal in what you accept".
I will also open a PR in the AAA to remove the trailing space, in accordance to Postel's law
